export enum ActionType {
    ADD_TO_CART = "ADD_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    CLEAR_CART = "CLEAR_CART",
    LIST_ALL_PRODUCTS = "LIST_ALL_PRODUCTS",
    LIST_ALL_PRODUCTS_SUCCESS = "LIST_ALL_PRODUCTS_SUCCESS",
}